image:
  repository: "registry.hawer.eu/podinspector"
  tag: "latest"
  pullPolicy: IfNotPresent
overrideNamespace: "monitoring"

service:
  annotations: {}
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: traefik
  annotations: {}

podAnnotations:
  k8s.grafana.com/scrape: 'true'
  k8s.grafana.com/metrics.path: '/metrics'
  k8s.grafana.com/job: "PodInspector"
  k8s.grafana.com/metrics.portNumber: "8080"