mode: standalone
rootUser: lgtm
rootPassword: supersecret
buckets:
  # Default Tempo storage bucket.
  - name: tempo-traces
    policy: none
    purge: false
  # Bucket for traces storage if enterprise.enabled is true - requires license.
  # - name: enterprise-traces
  #   policy: none
  #   purge: false
  # Admin client bucket if enterprise.enabled is true - requires license.
  # - name: enterprise-traces-admin
  #   policy: none
  #   purge: false
  - name: loki-chunks
    policy: none
    purge: false
  - name: loki-ruler
    policy: none
    purge: false
  - name: mimir-tsdb
    policy: none
    purge: false
  - name: mimir-blocks
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
persistence:
  enabled: true
  size: 2Gi
  storageClass: local-path 
resources:
  requests:
    cpu: 100m
    memory: 128Mi
# Changed the mc config path to '/tmp' from '/etc' as '/etc' is only writable by root and OpenShift will not permit this.
configPathmc: '/tmp/minio/mc/'
address: null