apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.overrideNamespace | default .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pod-inspector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod-inspector
      annotations:
      {{- with .Values.podAnnotations }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ tpl $value $ | quote }}
      {{- end }}
      {{- end }}
    spec:
      containers:
        - name: podinspector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port | default 8080 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port | default 8080 }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.port | default 8080 }}    
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
      serviceAccountName: {{ .Release.Name }}-service-account
