{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.overrideNamespace | default .Release.Namespace | quote }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range .Values.ingress.annotations }}
    {{- range $key, $value := . }}
      {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          - backend:
              service:
                name: {{ tpl .name $ }}
                port:
                  number: {{ .port | default "8080" }}
            pathType: {{ .pathType }}
            path: {{ .path }}
    {{- end }}
{{- end }}