name: release
on:
  workflow_run:
    workflows:
      - helm
      - python
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: helm-packages
          path: charts/packages
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: app/dist/*


      - name: Create GitHub Release with Helm package
        uses: softprops/action-gh-release@v2
        with:
          files: charts/packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}