name: Release

on:
  push:
    paths:
      - "app/**"
  pull_request:
    paths:
      - "app/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pythons-version }}
          cache: pip
      - run: pip install -r requirements.txt
      - run: pip install black flake8
      - run: black --check app/
      - run: flake8 app/

  build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install build
      - run: python -m build app
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: app/dist/*

